### 실습 : 좋아하는 과일 목록 5개를 만들고 라벨인코딩 해보기. 

In [16]:
list=['수박','메론','키위','블루베리','바나나']
num=[0,1,2,3,4]
수박=[1,0,0,0,0]
메론=[0,1,0,0,0]
키위=[0,0,1,0,0]
블루베리=[0,0,0,1,0]
바나나=[0,0,0,0,1]

In [1]:
import pandas as pd 

data={'eng':['b','c','a','d']}
df=pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

In [2]:
type(df.eng)

pandas.core.series.Series

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
encoder_x=LabelEncoder()
df['라벨']=encoder_x.fit_transform(df['eng'])
df

eng  라벨
0   b   1
1   c   2
2   a   0
3   d   3

### One-Hot Encoding 하기

In [41]:
ohe=OneHotEncoder(sparse=False)
y_oh=ohe.fit_transform(df['eng'].values.reshape(-1,1))
print(y_oh)
print(y_oh.shape)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
(4, 4)


### 실습 = 위에서 했던 과일들에 label&onehot encoding 해보기

In [36]:
data_f={'과일' : list}
d_f=pd.DataFrame(data_f)
print(type(d_f))
d_f

<class 'pandas.core.frame.DataFrame'>


과일
0    수박
1    메론
2    키위
3  블루베리
4   바나나

In [39]:
encoder_f=LabelEncoder()
d_f['라벨']=encoder_f.fit_transform(d_f['과일'])
d_f

과일  과일_메론  과일_바나나  과일_블루베리  과일_수박  과일_키위  라벨
0    수박      0       0        0      1      0   3
1    메론      1       0        0      0      0   0
2    키위      0       0        0      0      1   4
3  블루베리      0       0        1      0      0   2
4   바나나      0       1        0      0      0   1

In [26]:
onehot=OneHotEncoder()
val=d_f['과일'].values.reshape(-1,1)
y=onehot.fit_transform(val).toarray()
y

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [37]:
oh=pd.get_dummies(d_f)
oh

과일_메론  과일_바나나  과일_블루베리  과일_수박  과일_키위
0      0       0        0      1      0
1      1       0        0      0      0
2      0       0        0      0      1
3      0       0        1      0      0
4      0       1        0      0      0

In [38]:
d_f=pd.concat([d_f,oh],axis=1)
d_f

과일  과일_메론  과일_바나나  과일_블루베리  과일_수박  과일_키위
0    수박      0       0        0      1      0
1    메론      1       0        0      0      0
2    키위      0       0        0      0      1
3  블루베리      0       0        1      0      0
4   바나나      0       1        0      0      0